<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.messenger.handler_descriptor.tGvt0LH' shared service.

include_once \dirname(__DIR__, 7).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
include_once \dirname(__DIR__, 7).'/vendor/symfony/mailer/Messenger/MessageHandler.php';
include_once \dirname(__DIR__, 7).'/vendor/symfony/mailer/Transport/TransportInterface.php';
include_once \dirname(__DIR__, 7).'/vendor/symfony/mailer/Transport/Transports.php';
include_once \dirname(__DIR__, 7).'/vendor/symfony/mailer/Transport.php';

return $this->privates['.messenger.handler_descriptor.tGvt0LH'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \Symfony\Component\Mailer\Messenger\MessageHandler((new \Symfony\Component\Mailer\Transport(new RewindableGenerator(function () {
    yield 0 => ($this->privates['mailer.transport_factory.null'] ?? $this->load('getMailer_TransportFactory_NullService.php'));
    yield 1 => ($this->privates['mailer.transport_factory.sendmail'] ?? $this->load('getMailer_TransportFactory_SendmailService.php'));
    yield 2 => ($this->privates['mailer.transport_factory.smtp'] ?? $this->load('getMailer_TransportFactory_SmtpService.php'));
}, 3)))->fromStrings(['main' => 'smtp://null'])), []);
