<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.messenger.handler_descriptor.vMw0m61' shared service.

include_once \dirname(__DIR__, 7).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
include_once \dirname(__DIR__, 7).'/vendor/symfony/notifier/Messenger/MessageHandler.php';
include_once \dirname(__DIR__, 7).'/vendor/symfony/notifier/Transport/TransportInterface.php';
include_once \dirname(__DIR__, 7).'/vendor/symfony/notifier/Transport/Transports.php';
include_once \dirname(__DIR__, 7).'/vendor/symfony/notifier/Transport.php';

return $this->privates['.messenger.handler_descriptor.vMw0m61'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \Symfony\Component\Notifier\Messenger\MessageHandler((new \Symfony\Component\Notifier\Transport(new RewindableGenerator(function () {
    yield 0 => ($this->privates['notifier.transport_factory.null'] ?? $this->load('getNotifier_TransportFactory_NullService.php'));
}, 1)))->fromStrings([])), []);
