<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Shared\Infrastructure\Symfony\ApiExceptionListener' shared autowired service.

include_once \dirname(__DIR__, 7).'/src/Shared/Infrastructure/Symfony/ApiExceptionListener.php';
include_once \dirname(__DIR__, 7).'/src/Shared/Infrastructure/Symfony/ApiExceptionsHttpStatusCodeMapping.php';

return $this->privates['App\\Shared\\Infrastructure\\Symfony\\ApiExceptionListener'] = new \App\Shared\Infrastructure\Symfony\ApiExceptionListener(new \App\Shared\Infrastructure\Symfony\ApiExceptionsHttpStatusCodeMapping());
