<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'messenger.bus.default.middleware.handle_message' shared service.

include_once \dirname(__DIR__, 7).'/vendor/symfony/messenger/Middleware/MiddlewareInterface.php';
include_once \dirname(__DIR__, 7).'/vendor/psr/log/Psr/Log/LoggerAwareTrait.php';
include_once \dirname(__DIR__, 7).'/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php';
include_once \dirname(__DIR__, 7).'/vendor/symfony/messenger/Handler/HandlersLocatorInterface.php';
include_once \dirname(__DIR__, 7).'/vendor/symfony/messenger/Handler/HandlersLocator.php';

$this->privates['messenger.bus.default.middleware.handle_message'] = $instance = new \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware(new \Symfony\Component\Messenger\Handler\HandlersLocator(['Symfony\\Component\\Mailer\\Messenger\\SendEmailMessage' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['.messenger.handler_descriptor.tGvt0LH'] ?? $this->load('get_Messenger_HandlerDescriptor_TGvt0LHService.php'));
}, 1), 'Symfony\\Component\\Notifier\\Message\\ChatMessage' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['.messenger.handler_descriptor.vMw0m61'] ?? $this->load('get_Messenger_HandlerDescriptor_VMw0m61Service.php'));
}, 1), 'Symfony\\Component\\Notifier\\Message\\SmsMessage' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['.messenger.handler_descriptor.XZowc.T'] ?? $this->load('get_Messenger_HandlerDescriptor_XZowc_TService.php'));
}, 1)]));

$instance->setLogger(($this->privates['logger'] ?? ($this->privates['logger'] = new \Symfony\Component\HttpKernel\Log\Logger())));

return $instance;
