<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'notifier.transport_factory.null' shared service.

include_once \dirname(__DIR__, 7).'/vendor/symfony/notifier/Transport/TransportFactoryInterface.php';
include_once \dirname(__DIR__, 7).'/vendor/symfony/notifier/Transport/AbstractTransportFactory.php';
include_once \dirname(__DIR__, 7).'/vendor/symfony/notifier/Transport/NullTransportFactory.php';

return $this->privates['notifier.transport_factory.null'] = new \Symfony\Component\Notifier\Transport\NullTransportFactory(($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->privates['http_client'] ?? $this->load('getHttpClientService.php')));
