framework:
  test: true

services:
  _defaults:
    autoconfigure: true
    autowire: true

  CodelyTv\Tests\:
    resource: '../../../../tests/src'

  # -- IMPLEMENTATIONS SELECTOR --
  CodelyTv\Shared\Domain\Bus\Event\EventBus: '@App\Shared\Infrastructure\Bus\Event\InMemory\InMemorySymfonyEventBus'
